### ISSUE TITLE
Parser for .osc files 

### ISSUE THREAD

**Issue by geohacker** [mapbox/osm-comments-parser#27]
I think we can extend the scope this project to also parse .osc files. These are minutely, hourly or [daily replication files](http://planet.openstreetmap.org/replication/minute/) that contains changes that happened to features for that period of time. The goal is:

* to move the osm-edit-report parser to this project 
* and consolidate parsing and prepare reliable metrics for osm edits. 

@batpad - let's outline steps for the parser here. 

cc @Rub21 @ajithranka

**Comment by batpad** [comment]
- Create a new folder to hold code for this parser, probably call it `replication`, similar in structure to `changesets` or `notes` - eg https://github.com/mapbox/osm-comments-parser/tree/master/changesets

 - The `changesets` processing code includes some complexity to handle writing CSVs for initial back-fill. We probably don't need that here and can ignore those bits of code.

 - Make schema changes and changes to indexes: https://github.com/mapbox/osm-comments-parser/tree/master/scripts -- not sure if we want to have some sort of "migration" script to be able to migrate the current DB with the schema changes.

 - Add option to process `replication` files in `index.js`: https://github.com/mapbox/osm-comments-parser/blob/master/index.js#L127

 - Write tests for your parser: see https://github.com/mapbox/osm-comments-parser/tree/master/test for current tests

 - Publish a new `npm` version and 🚢 . Then, we can move onto integration into `comments-watchbot` and the API.

**Comment by batpad** [comment]
@geohacker - this looks done! Can we close?

**Comment by geohacker** [comment]
YES! Thank you everyone!
