### ISSUE TITLE
Wrong timestamp 

### ISSUE THREAD

**Issue by kepta** [mapbox/osm-comments-parser#32]
On querying the server with the following params https://osm-comments-api.mapbox.com/api/v1/stats?from=2017-03-13T00:00:00.000Z&to=2017-03-13T22:59:59.000Z

We get an interesting result,
It returns a [changeset:39292039](https://osmcha.mapbox.com/39292039/) which was created back in 2016.

As per conversation with @geohacker we have identified the code that might be creating this problem.
https://github.com/mapbox/osm-comments-parser/blob/master/changes/counter.js#L22

cc @geohacker

**Comment by geohacker** [comment]
@kepta thank you and sorry for this bug. I think we are better off using this https://github.com/osmcode/node-osmium/blob/master/doc/tutorial.md#getting-the-file-header to get the reliable timestamp.

**Comment by kepta** [comment]
This has been implemented. 
Closing this ticket.
