### ISSUE TITLE
failed install

### ISSUE THREAD

**Issue by tosseto** [mapbox/osm-comments-parser#44]
I failed npm install, because I guess failed download node-pre-gyp ??

**>node-pre-gyp ERR! Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/osmium/v0.5.6/node-v59-darwin-x64.tar.gz** 

/usr/local/bin/node /usr/local/lib/node_modules/npm/bin/npm-cli.js install --scripts-prepend-node-path=auto

> osmium@0.5.6 preinstall /Users/antoine/Documents/osm-comments-parser/node_modules/osmium
> npm install node-pre-gyp

+ node-pre-gyp@0.6.39
  added 113 packages in 2.847s
  npm notice created a lockfile as package-lock.json. You should commit this file.

> osmium@0.5.6 install /Users/antoine/Documents/osm-comments-parser/node_modules/osmium
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/osmium/v0.5.6/node-v59-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for osmium@0.5.6 and node@9.6.1 (node-v59 ABI, unknown) (falling back to source compile with node-gyp) 
  CXX(target) Release/obj.target/osmium/src/apply.o
In file included from ../src/apply.cpp:6:
In file included from ../../nan/nan.h:192:
../../nan/nan_maybe_43_inl.h:112:15: warning: 'ForceSet' is deprecated [-Wdeprecated-declarations]
  return obj->ForceSet(isolate->GetCurrentContext(), key, value, attribs);
              ^
/Users/antoine/.node-gyp/9.6.1/include/node/v8.h:3164:3: note: 'ForceSet' has been explicitly marked deprecated here
  V8_DEPRECATED("Use CreateDataProperty / DefineOwnProperty",
  ^
/Users/antoine/.node-gyp/9.6.1/include/node/v8config.h:321:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
In file included from ../src/apply.cpp:17:
In file included from ../src/location_handler_wrap.hpp:11:
In file included from ../../libosmium/include/osmium/index/map/all.hpp:43:
../../libosmium/include/osmium/index/map/sparse_mem_table.hpp:42:10: fatal error: 'google/sparsetable' file not found
#include <google/sparsetable>
         ^~~~~~~~~~~~~~~~~~~~
1 warning and 1 error generated.
make: *** [Release/obj.target/osmium/src/apply.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:127:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
gyp ERR! System Darwin 17.4.0
gyp ERR! command "/usr/local/Cellar/node/9.6.1/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/antoine/Documents/osm-comments-parser/node_modules/osmium/lib/binding/osmium.node" "--module_name=osmium" "--module_path=/Users/antoine/Documents/osm-comments-parser/node_modules/osmium/lib/binding"
gyp ERR! cwd /Users/antoine/Documents/osm-comments-parser/node_modules/osmium
gyp ERR! node -v v9.6.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/Cellar/node/9.6.1/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/antoine/Documents/osm-comments-parser/node_modules/osmium/lib/binding/osmium.node --module_name=osmium --module_path=/Users/antoine/Documents/osm-comments-parser/node_modules/osmium/lib/binding' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/antoine/Documents/osm-comments-parser/node_modules/osmium/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:127:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:933:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
node-pre-gyp ERR! System Darwin 17.4.0
node-pre-gyp ERR! command "/usr/local/Cellar/node/9.6.1/bin/node" "/Users/antoine/Documents/osm-comments-parser/node_modules/osmium/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/antoine/Documents/osm-comments-parser/node_modules/osmium
node-pre-gyp ERR! node -v v9.6.1
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/Cellar/node/9.6.1/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/antoine/Documents/osm-comments-parser/node_modules/osmium/lib/binding/osmium.node --module_name=osmium --module_path=/Users/antoine/Documents/osm-comments-parser/node_modules/osmium/lib/binding' (1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! osmium@0.5.6 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the osmium@0.5.6 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/antoine/.npm/_logs/2018-03-01T06_44_47_805Z-debug.log

Process finished with exit code 1

**Comment by geohacker** [comment]
@tosseto it's likely failing because of your node version. Could you try node version 4? I think the osmium bindings aren't available for node 9.

**Comment by tosseto** [comment]
Great thank you !
I was success extract osm-notes !
