### ISSUE TITLE
Optimize initial load of changesets

### ISSUE THREAD

**Issue by batpad** [mapbox/osm-comments-parser#5]
While the current parser code works well for incremental changeset updates, it is not ideally suited to the initial load of ~40 million changeset records. This can be quite slow and we would ideally load data into postgres via `ogr2ogr` or a `\COPY` directly from a CSV rather than making multiple `INSERT`s.

Approach would be for the changeset parser to take an option like `initial=true` which would make it generate CSV files instead of writing to the database. The CSV files would then be loaded via `\COPY` or `ogr2ogr`

/cc @geohacker

**Comment by rclark** [comment]
cc @ian29 for insight into his prior art loading large amounts of data into postgres using javascript. Anything structural from your work reusable in a different context (i.e. not loading geojson)?

**Comment by ian29** [comment]
@batpad @rclark i'm not opposed to making a more generic "stream-stuff-into-postgres" project. 

@batpad also: unless you need to insert geometry blobs, you maybe want to checkout https://github.com/brianc/node-pg-copy-streams. i had a tough time generating wkb geometry in js (required for COPY statements), but there are probably ways around this.

**Comment by batpad** [comment]
@ian29 wow node-pg-copy-streams seems really cool, did not know one could do that. Right now, I'm just generating a CSV file and loading it in with `\COPY` into postgres. This works fine and is at least much more efficient than multiple `INSERT`s. For the geometries, I just run the `UPDATE` to populate the geom field after the CSV is loaded and since it's a single `UPDATE` it is pretty fast (about 5 mins for 34.7 million rows).

With the generating of CSV files and using `\COPY`, the initial load time for 34.7 million changesets is down from about 48 hours on an ec2 x4.large to about 3 hours on my laptop - I feel this is fine for our current use-case and I think will punt further optimizations for later.

@ian29 I would really love to go through my code that parses the XML and writes into postgres at some point - I know it could probably be a lot more efficient - I'm just about wrapping my head around node streams, etc. For now though, I feel the times are all at acceptable levels for what we're doing and I think it makes sense to move forward with building out the app and perhaps revisiting this down the line. However, if you do get the chance to go through code, please do flag stuff that looks suboptimal.

**Comment by batpad** [comment]
This is done, the changeset processFile function now accepts an `initial=true` parameter, which generates a CSV file which can be directly loaded into the db with `\COPY`.
